apiVersion: v1
kind: Secret
metadata:
  name: holiday-secrets
  namespace: holiday
type: Opaque
stringData:
  POSTGRES_PASSWORD: "holiday"
  NEO4J_AUTH: "neo4j/holiday_neo4j"
  DATATOURISME_API_KEY: "98bf037a-4b11-4645-aa93-ec008b57f911"